services:
  app:
      image: ajikamaludin/php83user:latest
      container_name: autoparts-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
        - ./user.ini:/usr/local/etc/php/php.ini
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
      networks:
        - autoparts
  nginx:
    image: nginx:1.17-alpine
    container_name: autoparts-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      - autoparts
      
networks:
  autoparts:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.99.11.0/24
            gateway: 10.99.11.1
